app/employee/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'employee_blueprint',
    __name__,
    url_prefix=''
)

app/employee/routes.py
from itertools import count
from app.employee import blueprint
from flask import render_template
from flask_login import login_required
from app.models import Employee, Assigned, Job, Phone, TempEmployee, RegEmployee, Users
from flask_login import current_user
# Employee Dashboard Routes


@blueprint.route('/employee/dashboard')
@login_required
def employee_index():
    users = Users.query.filter_by(id=current_user.id).first()
    if users.manager == True:
        manager_button = True
    else:
        manager_button = False
    user = current_user.id
    jobs_assigned = Assigned.query.filter(
        Assigned.fk_employee == user)
    current_job = Assigned.query.filter(
        Assigned.fk_employee == user, Assigned.end_date == None)
    count = Assigned.query.filter(
        Assigned.fk_employee == user, Assigned.end_date == None).count()
    temp_employee = TempEmployee.query.filter_by(fk_trn=user).first()
    reg_employee = RegEmployee.query.filter_by(fk_trn=user).first()
    if reg_employee:
        pay = f'${int(reg_employee.yearly_salary)}'
        employee = Employee.query.filter_by(trn=user).first()
        auditor_id = f'TRN:{employee.auditor}'
        auditor = employee.auditor
        user_auditor = Employee.query.filter_by(trn=auditor).first()
        if auditor != None:
            auditor_name = f'{user_auditor.first_name} {user_auditor.last_name}'
            return render_template('employee/dashboard.html', segment='Dashboard',
                                   paytype='Salary', jobs_assigned=jobs_assigned, pay=pay,
                                   current_job=current_job, auditor_id=auditor_id, auditor_name=auditor_name,
                                   manager_button=manager_button, count=count)
        else:
            auditor_id = 'No Auditor Is Assigned'
            return render_template('employee/dashboard.html', segment='Dashboard', paytype='Salary',
                                   jobs_assigned=jobs_assigned, pay=pay, current_job=current_job,
                                   auditor_id=auditor_id, manager_button=manager_button, count=count)

    elif temp_employee:
        tempemployee = TempEmployee.query.filter_by(fk_trn=user).first()
        pay = f'${int(tempemployee.hr_wage)}'
        employee = Employee.query.filter_by(trn=user).first()
        auditor_id = f'trn:{employee.auditor}'
        auditor = employee.auditor
        user_auditor = Employee.query.filter_by(trn=auditor).first()
        if auditor != None:
            auditor_name = f'{user_auditor.first_name} {auditor.last_name}'
            return render_template('employee/dashboard.html', segment='Dashboard', paytype='Hourly Wage',
                                   jobs_assigned=jobs_assigned, pay=pay, current_job=current_job,
                                   auditor_id=auditor_id, auditor_name=auditor_name, count=count)
        else:
            auditor_id = 'No Auditor Is Assigned'
            return render_template('employee/dashboard.html', segment='Dashboard', paytype='Hourly Wage',
                                   jobs_assigned=jobs_assigned, pay=pay, current_job=current_job,
                                   auditor_id=auditor_id, count=count)

# Employee's Jobs


@blueprint.route('/employee/jobs')
@login_required
def jobs():
    jobs_assigned = Assigned.query.filter(
        Assigned.fk_employee == current_user.id)
    return render_template('employee/job.html', segment='index', jobs_assigned=jobs_assigned)

# Employee Profile


@blueprint.route('/employee/profile')
@login_required
def profile():
    user = current_user.id
    employee = Employee.query.filter_by(trn=user).first()
    first_name = employee.first_name
    last_name = employee.last_name
    city = employee.city
    parish = employee.parish
    phone = Phone.query.filter(Phone.fk_trn == current_user.id)
    if employee.street_num == None:
        return render_template('employee/profile.html', segment='index', phone=phone, user=user, employee=employee, first_name=first_name, last_name=last_name, parish=parish, city=city)
    return render_template('employee/profile.html', segment='index', phone=phone, user=user, employee=employee, first_name=first_name, last_name=last_name, parish=parish, city=city)

# Emplyoee View Job Function


@blueprint.route('/employee/view-job/<string:id>')
@login_required
def view_job(id):
    job = Job.query.filter_by(ref_number=id).first()
    return render_template('employee/view-job.html', job=job, segment='View Job')

# Employee Supervisor Portal


@blueprint.route('/employee/supervisor-portal')
@login_required
def supervisor_portal():
    job = Job.query.filter_by(fk_supervisor=current_user.id).first()
    if job:
        return render_template('employee/supervisor.html', msg='Below are a list of jobs you are supervising', job=job, segment='Supervisor Portal')
    else:
        return render_template('employee/supervisor.html', msg='You are not currently a supervisor', job=job, segment='Supervisor Portal')



@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('error/page-403.html'), 403


@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('error/page-404.html'), 404


@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('error/page-500.html'), 500

app/templates/employee/dashboard.html
{% extends "layouts/employee/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <br>
    <div class="row">
        <div class="col-12 col-sm-6 col-xl-4 mb-4">
            <div class="card border-0 shadow">
                <div class="card-body">
                    <div class="row d-block d-xl-flex align-items-center">
                        <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                            <div class="icon-shape icon-shape-primary rounded me-4 me-sm-0">
                                <svg class="icon" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z"></path></svg>
                            </div>
                        </div>
                        <div class="col-12 col-xl-7 px-xl-0">
                            <div class="d-none d-sm-block">
                                <h2 class="h6 text-gray-400 mb-0">{{paytype}}</h2>
                                <h3 class="fw-extrabold mb-2">{{pay}}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-xl-4 mb-4">
            <div class="card border-0 shadow">
                <div class="card-body">
                    <div class="row d-block d-xl-flex align-items-center">
                        <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                            <div class="icon-shape icon-shape-secondary rounded me-4 me-sm-0">
                                <img src="/static/assets/img/illustrations/employee.svg">
                            </div>
                            <div class="d-sm-none">
                                <h2 class="fw-extrabold h5">Revenue</h2>
                            </div>
                        </div>
                        <div class="col-12 col-xl-7 px-xl-0">
                            <div class="d-none d-sm-block">
                                <h2 class="h6 text-gray-400 mb-0">Auditor</h2>
                                <h3 class="fw-extrabold mb-2">{{auditor_name}}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-xl-4 mb-4">
            <div class="card border-0 shadow">
                <div class="card-body">
                    <div class="row d-block d-xl-flex align-items-center">
                        <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                            <div class="icon-shape icon-shape-tertiary rounded me-4 me-sm-0">
                                <img src="/static/assets/img/illustrations/job.svg">
                            </div>
                            <div class="d-sm-none">
                                <h2 class="fw-extrabold h5"> Current Jobs </h2>
                            </div>
                        </div>
                        <div class="col-12 col-xl-7 px-xl-0">
                            <div class="d-none d-sm-block">
                                <h2 class="h6 text-gray-400 mb-0"> Current Jobs</h2>
                                <h3 class="fw-extrabold mb-2">{{count}}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card border-0 shadow">
        <div class="card-body">
            <div class="table-responsive">
                <table id="datatablesSimple" class="table table-centered table-nowrap mb-0 rounded">
                    <thead class="thead-light">
                        <tr>
                            <th class="border-0 rounded-start"> Job ID</th>
                            <th class="border-0"> Date Assigned</th>
                            <th class="border-0">Start Date</th>
                            <th class="border-0 rounded-end">Options</th>
                        </tr>
                    </thead>
                    <tbody>
                        <!-- Item -->
                        {% for current_job in current_job %}
                        <tr>
                            <td class="border-0">                                             
                                <a href="#" class="d-flex align-items-center">
                                    <div><span class="h6">{{ current_job.fk_job }}</span></div>
                                </a>
                            </td>
                            <td class="border-0">                                             
                                <a href="#" class="d-flex align-items-center">
                                    <div><span class="h6">{{ current_job.date_assigned }}</span></div>
                                </a>
                            </td>
                            <td class="border-0">                                             
                                <a href="#" class="d-flex align-items-center">
                                    <div><span class="h6">{{ current_job.start_date }}</span></div>
                                </a>
                            </td>
                            <td> 
                                <a class="btn btn-primary" href="{{url_for('employee_blueprint.view_job', id=current_job.fk_job)}}" role="button">View</a>
                            </td>
                        </tr>
                        {% endfor %}
                        <!-- End of Item -->
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %} 
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="/static/assets/js/datatables-simple-demo.js"></script>
{% endblock javascripts %}

app/templates/employee/job.html
{% extends "layouts/employee/base.html" %}

{% block title %} Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="py-4">
      <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
          <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
              <li class="breadcrumb-item">
                  <a href="#">
                      <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                  </a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">Jobs</li>
          </ol>
      </nav>
      <div class="d-flex justify-content-between w-100 flex-wrap">
          <div class="mb-3 mb-lg-0">
              <h1 class="h4">Job Assigned Table</h1>
              <p class="mb-0">Below are a list of all the jobs you have been assigned to.</p>
          </div>
      </div>
  </div>

  <div class="card border-0 shadow">
      <div class="card-body">
          <div class="table-responsive">
              <table id="datatablesSimple" class="table table-centered table-nowrap mb-0 rounded">
                  <thead class="thead-light">
                      <tr>
                          <th class="border-0 rounded-start">Job ID</th>
                          <th class="border-0">Date Assigned</th>
                          <th class="border-0">Start Date</th>
                          <th class="border-0 rounded-end">End Date</th>
                      </tr>
                  </thead>
                  <tbody>
                      <!-- Item -->
                      {% for job in jobs_assigned %}
                      <tr>
                          <td class="border-0">                                             
                              <a href="#" class="d-flex align-items-center">
                                  <div><span class="h6">{{ job.fk_job }}</span></div>
                              </a>
                          </td>
                          <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ job.date_assigned }}</span></div>
                            </a>
                        </td>
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ job.start_date }}</span></div>
                            </a>
                        </td>
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ job.end_date }}</span></div>
                            </a>
                        </td>
                      </tr>
                      <!-- End of Item -->
                      {% endfor %}
                  </tbody>
              </table>
          </div>
      </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="/static/assets/js/datatables-simple-demo.js"></script>

{% endblock javascripts %}

app/templates/employee/profile.html
{% extends "layouts/employee/base.html" %} {% block title %} Settings {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4"
>
</div>
<div class="row">
  <div class="col-12 col-xl-8">
    <div class="card card-body border-0 shadow mb-4">
      <h2 class="h5 mb-4">General information</h2>
      <form>
        <div class="row">
          <div class="col-md-6 mb-3">
            <div>
              <label for="first_name">First Name</label>
              <input type="text" id="input-first-name" class="form-control"value = "{{ first_name }}" readonly>
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <div>
              <label for="last_name">Last Name</label>
              <input type="text" id="input-last-name" class="form-control"value = "{{ last_name }}" readonly>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-6 mb-3">
            <div class="form-group">
              <label for="email">Email</label>
              <input
                class="form-control"
                id="email"
                type="email"
                placeholder="name@company.com"
                value="{{ current_user.email }}"
                readonly
              />
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <div class="form-group">
              <label for="phone">Phone</label>
              <input
                class="form-control"
                id="phone"
                type="number"
                value="{{ phone.phone_number }}"
                readonly
              />
            </div>
          </div>
        </div>
        <h2 class="h5 my-4">Location</h2>
        <div class="row">
          <div class="col-sm-3 mb-3">
            <div class="form-group">
              <label for="number">Number</label>
              <input
                class="form-control"
                id="number"
                type="number"
                value="{{employee.street_num}}"
                readonly
              />
            </div>
          </div>
          <div class="col-sm-9 mb-3">
            <div class="form-group">
              <label for="address">Address</label>
              <input
                class="form-control"
                id="address"
                type="text"
                value="{{employee.street_name}}"
                readonly
              />
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4 mb-3">
            <div class="form-group">
              <label for="city">City</label>
              <input
                class="form-control"
                id="city"
                type="text"
                value="{{employee.city}}"
                readonly
              />
            </div>
          </div>
          <div class="col-sm-4 mb-3">
            <label for="state">Parish</label>
            <input
                class="form-control"
                id="parish"
                type="text"
                value="{{employee.parish}}"
                readonly
              />
          </div>
        </div>
        <div class="mt-3">
          <button class="btn btn-gray-800 mt-2 animate-up-2" type="submit">
            Save all
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/templates/employee/supervisor.html
{% extends "layouts/employee/base.html" %}

{% block title %} Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="py-4">
      <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
          <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
              <li class="breadcrumb-item">
                  <a href="#">
                      <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                  </a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">Jobs</li>
          </ol>
      </nav>
      <div class="d-flex justify-content-between w-100 flex-wrap">
          <div class="mb-3 mb-lg-0">
              <h1 class="h4">Jobs</h1>
              <p class="mb-0">Below are a list of all the jobs you are a supervisor for to.</p>
          </div>
      </div>
  </div>

  <div class="card border-0 shadow">
      <div class="card-body">
          <div class="table-responsive">
              <table id="datatablesSimple" class="table table-centered table-nowrap mb-0 rounded">
                  <thead class="thead-light">
                      <tr>
                          <th class="border-0 rounded-start">Supervisor</th>
                          <th class="border-0">Job ID</th>
                          <th class="border-0">Start Date</th>
                          <th class="border-0">End Date</th>
                          <th class="border-0">Description</th>
                          <th class="border-0 rounded-end">Option</th>
                      </tr>
                  </thead>
                  <tbody>
                      <!-- Item -->
                      {%for job in jobs%}
                      <tr>
                          <td class="border-0">                                             
                              <a href="#" class="d-flex align-items-center">
                                  <div><span class="h6">{{ job.fk_supervisor }}</span></div>
                              </a>
                          </td>
                          <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ job.ref_number }}</span></div>
                            </a>
                        </td>
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ job.job_start_date }}</span></div>
                            </a>
                        </td>
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ job.job_end_date }}</span></div>
                            </a>
                        </td>
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ job.description }}</span></div>
                            </a>
                        </td>
                        <td> 
                            <a class="btn btn-primary" href="{{url_for('employee_blueprint.view_job', id=job.ref_number)}}" role="button">View</a>
                        </td>
                      </tr>
                      <!-- End of Item -->
                    {%endfor%}
                  </tbody>
              </table>
          </div>
      </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="/static/assets/js/datatables-simple-demo.js"></script>

{% endblock javascripts %}

app/templates/employee/view-job.html
{% extends "layouts/employee/base.html" %} {% block title %} Settings {% endblock %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<div
  class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center py-4"
>
</div>
<div class="row">
  <div class="col-12 col-xl-8">
    <div class="card card-body border-0 shadow mb-4">
      <h2 class="h5 mb-4">General information</h2>
      <form>
        <div class="row">
          <div class="col-md-6 mb-3">
            <div>
              <label for="job">Job ID</label>
              <input type="text" id="input-first-name" class="form-control"value = "{{ job.ref_number }}" readonly>
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <div>
              <label for="start_date">Start Date</label>
              <input type="text" id="input-last-name" class="form-control"value = "{{ job.job_start_date }}" readonly>
            </div>
          </div>
          <div class="col-md-6 mb-3">
            <div>
              <label for="start_date">End Date</label>
              <input type="text" id="input-last-name" class="form-control"value = "{{ job.job_end_date }}" readonly>
            </div>
          </div>
        </div>
        <h2 class="h5 my-4">Location</h2>
        <div class="row">
          <div class="col-sm-3 mb-3">
            <div class="form-group">
              <label for="number">Street Number</label>
              <input
                class="form-control"
                id="number"
                type="number"
                value="{{job.street_num}}"
                readonly
              />
            </div>
          </div>
          <div class="col-sm-9 mb-3">
            <div class="form-group">
              <label for="address">Address</label>
              <input
                class="form-control"
                id="address"
                type="text"
                value=" {{job.street_name}}"
                readonly
              />
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-4 mb-3">
            <div class="form-group">
              <label for="city">City</label>
              <input
                class="form-control"
                id="city"
                type="text"
                value=" {{job.city}}"
                readonly
              />
            </div>
          </div>
          <div class="col-sm-4 mb-3">
            <label for="parish">Parish</label>
            <input
                class="form-control"
                id="parish"
                type="text"
                value="{{job.parish}}"
                readonly
              />
          </div>
          <div class="col-sm-4 mb-3">
            <label for="supervisor">Supervisor</label>
            <input
                class="form-control"
                id="parish"
                type="number"
                value="{{job.fk_supervisor}}"
                readonly
              />
          </div>
          <div class="col-sm-4 mb-3">
            <label for="description">Description</label>
            <input
                class="form-control"
                id="parish"
                type="text" 
                rows="4" 
                value="{{job.description}}"
                readonly
              />
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}