app/manager/forms.py

from tokenize import String
from xml.etree.ElementTree import Comment
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, PasswordField, SubmitField, StringField, DecimalField, IntegerField
from wtforms.validators import DataRequired, Email


class CreateEmployee(FlaskForm):
    trn = StringField('trn', id='trn_create', validators=[DataRequired()])

    first_name = StringField(
        'first name', id='first_name_create', validators=[DataRequired()])

    last_name = StringField('Last Name', id='last_name_create',
                            validators=[DataRequired()])

    street_number = StringField(
        'street number', id='street_number_create')

    street_name = StringField(
        'street name', id='street_name_create', validators=[DataRequired()])

    city = StringField('city', id='city_create', validators=[DataRequired()])

    phone = IntegerField('phone', id='phone_create',
                         validators=[DataRequired()])

    parish = StringField('parish', id='last_name_create',
                         validators=[DataRequired()])

    auditor = StringField('auditor', id='auditor_create')

    hiring_date = DateField('start_date', validators=[DataRequired()])

    yearly_salary = DecimalField('yearly_salary', validators=[DataRequired()])

    hr_wage = DecimalField('hr_wage', validators=[DataRequired()])

    contract = StringField('contract', validators=[DataRequired()])


class CreateJob(FlaskForm):
    job_start = DateField('start_date', validators=[DataRequired()])

    street_number = StringField(
        'street number', id='street_number_create')

    street_name = StringField(
        'street name', id='street_name_create', validators=[DataRequired()])

    city = StringField('city', id='city_create', validators=[DataRequired()])

    parish = StringField('parish', id='last_name_create',
                         validators=[DataRequired()])

    description = StringField(
        'description', id='job_description', validators=[DataRequired()])

    supervisor = StringField(
        'supervisor', id='supervisor_create', validators=[DataRequired()])

    original_job = StringField(
        'original job', id='job_description')

class ResolveComplaint(FlaskForm):
    comment = StringField('comment', id='managers_comment', validators=[DataRequired()])
    
class EndJob(FlaskForm):
    end_date = DateField('end_date', validators=[DataRequired()])
    # Password recovery form


class PasswordRecoveryForm(FlaskForm):
    password_1 = PasswordField(label='Password')
    password_2 = PasswordField(label='Confirm Password')


class PromoteRegularForm(FlaskForm):
    yearly_salary = DecimalField('yearly_salary', validators=[DataRequired()])


class PromoteTemporaryForm(FlaskForm):
    hr_wage = DecimalField('hr_wage', validators=[DataRequired()])
    contract = StringField('contract', validators=[DataRequired()])

app/manager/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'manager_blueprint',
    __name__,
    url_prefix=''
)

app/manager/routes.py
import random
from flask_mail import Message
from flask_wtf import FlaskForm
from sqlalchemy import false
from app.auth.forms import OtpForm
from app.manager import blueprint
from flask import redirect, render_template, request, url_for
from flask_login import login_required
from app.models import Complaint, Employee, Assigned, TempEmployee, RegEmployee, Phone, Job, Users
from flask_login import current_user
from app import db, mail
from wtforms import DateField, RadioField
from wtforms.validators import DataRequired
from app.manager.forms import CreateEmployee, CreateJob, EndJob, PromoteRegularForm, PromoteTemporaryForm, ResolveComplaint
from sqlalchemy.sql import text

@blueprint.route('/manager/dashboard')
@login_required
def manager():
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        limit = 4
        employee = Employee.query.filter(Employee.trn != None).all()
        employee_count = Employee.query.count()
        job_count = Job.query.filter_by(job_end_date=None).count()
        complaint = Complaint.query.filter(Complaint.resolved == False).all()
        complaint_count = Complaint.query.filter_by(resolved= False).count()
        job = Job.query.filter(Job.job_end_date == None).all()
        return render_template('manager/dashboard.html', segment='dashboard', limit=limit, job=job,complaint=complaint, employee_count=employee_count, job_count=job_count, complaint_count=complaint_count, employee=employee)
    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/jobs')
@login_required
def manage_jobs():
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        jobs = Job.query.filter(Job.ref_number != None).all()
        return render_template('manager/job.html', segment='jobs', jobs=jobs)
    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/supervisors')
@login_required
def supervisors():
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        jobs = Job.query.filter(Job.ref_number != None)
        return render_template('manager/supervisor.html', segment='supervisor', jobs=jobs)
    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/assigned')
@login_required
def assigned():
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        jobs_assigned = Assigned.query.filter(Assigned.fk_employee != None)
        return render_template('manager/assigned.html', segment='index', jobs_assigned=jobs_assigned)
    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/employees')
@login_required
def manage_employees():
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        all_employees = Employee.query.filter(Employee.trn != None).all()
        return render_template('manager/manage-employees.html', segment='employees', all_employees=all_employees)
    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/promote-employee/<string:trn>')
@login_required
def promote_employee(trn):
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        regemployee = RegEmployee.query.filter_by(fk_trn=trn).first()
        if regemployee:
            return redirect(url_for('manager_blueprint.promote_regular_employee', trn=trn, segment='employees'))

        else:
            return redirect(url_for('manager_blueprint.promote_temporary_employee', trn=trn, segment='employees'))
    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/promote-temporary-employee/<string:trn>', methods=['GET', 'POST'])
@login_required
def promote_temporary_employee(trn):
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        form = PromoteTemporaryForm(request.form)
        tempemployee = TempEmployee.query.filter_by(fk_trn=trn).first()
        if 'add' in request.form:
            wage = request.form['hr_wage']
            contract = request.form['contract']
            employee = TempEmployee.query.filter_by(fk_trn=trn).update(
                dict(hr_wage=wage, contract_description=contract))
            db.session.commit()
            return redirect(url_for('manager_blueprint.manage_employees'))
        return render_template('manager/promote-temporary.html', form=form, segment='employees')
    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/promote-regular-employee/<string:trn>',  methods=['GET', 'POST'])
@login_required
def promote_regular_employee(trn):
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        regemployee = RegEmployee.query.filter_by(fk_trn=trn).first()
        form = PromoteRegularForm(request.form)
        if 'add' in request.form:
            salary = request.form['yearly_salary']
            employee = RegEmployee.query.filter_by(fk_trn=trn).update(
                dict(yearly_salary=salary))
            db.session.commit()
            return redirect(url_for('manager_blueprint.manage_employees'))
        return render_template('manager/promote-regular.html', form=form, segment='employees')

    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/view-employee/<string:trn>')
@login_required
def view_employee(trn):
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        regemployee = RegEmployee.query.filter_by(fk_trn=trn).first()
        if regemployee:
            return redirect(url_for('manager_blueprint.view_regular_employee', trn=trn))

        else:
            return redirect(url_for('manager_blueprint.view_temporary_employee', trn=trn))
    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/view-job/<string:id>')
@login_required
def view_jobs(id):
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        jobs = Job.query.filter_by(ref_number=id).first()
        return render_template('manager/view-jobs.html', jobs=jobs, segment='jobs')
    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/view-regular-employee/<string:trn>')
@login_required
def view_regular_employee(trn):
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        regemployee = RegEmployee.query.filter_by(fk_trn=trn).first()
        employee = Employee.query.filter_by(trn=trn).first()
        email = Users.query.filter_by(id=trn).first()
        trn = employee.trn
        first_name = employee.first_name
        last_name = employee.last_name
        street_number = employee.street_num
        street_name = employee.street_name
        city = employee.city
        parish = employee.parish
        auditor = employee.auditor
        hiring_date = regemployee.hiring_date
        salary = int(regemployee.yearly_salary)
        phone = Phone.query.filter(Phone.fk_trn == trn)
        if email:
            return render_template('manager/regular-employee-profile.html', segment='employee', email=email, phone=phone, trn=trn, employee=employee, first_name=first_name, last_name=last_name, street_number=street_number, street_name=street_name, parish=parish, city=city, auditor=auditor, salary=salary, hiring_date=hiring_date)
        else:
            return render_template('manager/regular-employee-profile.html', segment='employee', email='Employee Has Not Created Their Account', phone=phone, trn=trn, employee=employee, first_name=first_name, last_name=last_name, street_number=street_number, street_name=street_name, parish=parish, city=city, auditor=auditor, salary=salary, hiring_date=hiring_date)
    else:
        return redirect(url_for('employee_blueprint.employee_index'))


@blueprint.route('/manager/view-temporary-employee/<string:trn>')
@login_required
def view_temporary_employee(trn):
    user = Users.query.filter_by(id=current_user.id).first()
    if user.manager == True:
        tempemployee = TempEmployee.query.filter_by(fk_trn=trn).first()
        employee = Employee.query.filter_by(trn=trn).first()
        email = Users.query.filter_by(id=trn).first()
        trn = employee.trn
        first_name = employee.first_name
        last_name = employee.last_name
        street_number = employee.street_num
        street_name = employee.street_name
        city = employee.city
        parish = employee.parish
        auditor = employee.auditor
        hr_wage = tempemployee.hr_wage
        contract = tempemployee.contract_description
        phone = Phone.query.filter(Phone.fk_trn == trn)
        if email:
            return render_template('manager/temporary-employee-profile.html', segment='employee', email=email, phone=phone, trn=trn, employee=employee, first_name=first_name, last_name=last_name, street_number=street_number, street_name=street_name, parish=parish, city=city, auditor=auditor, hr_wage=hr_wage, contract=contract)
        else:
            return render_template('manager/temporary-employee-profile.html', segment='employee', email='Employee Has Not Created Their Account', phone=phone, trn=trn, employee=employee, first_name=first_name, last_name=last_name, street_number=street_number, street_name=street_name, parish=parish, city=city, auditor=auditor, hr_wage=hr_wage, contract=contract)
    else:
        return redirect(url_for('employee_blueprint.employee_index'))

@blueprint.route('/auth/otp/delete-employee/<string:trn>', methods=['GET','POST'])
def otp_verify_employee(trn):
    form = OtpForm(request.form)
    global otp
    if request.method == 'POST':
        

app/templates/manager/dashboard.html
{% extends "layouts/manager/base.html" %}

{% block title %} Dashboard {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
    <br>
    <div class="row">
        <div class="col-12 col-sm-6 col-xl-4 mb-4">
            <div class="card border-0 shadow">
                <div class="card-body">
                    <div class="row d-block d-xl-flex align-items-center">
                        <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                            <div class="icon-shape icon-shape-secondary rounded me-4 me-sm-0">
                                <img src="/static/assets/img/illustrations/employee.svg">
                            </div>
                            <div class="d-sm-none">
                            </div>
                        </div>
                        <div class="col-12 col-xl-7 px-xl-0">
                            <div class="d-none d-sm-block">
                                <h2 class="h6 text-gray-400 mb-0">Employees Count</h2>
                                <h3 class="fw-extrabold mb-2">{{employee_count}}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-xl-4 mb-4">
            <div class="card border-0 shadow">
                <div class="card-body">
                    <div class="row d-block d-xl-flex align-items-center">
                        <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                            <div class="icon-shape icon-shape-secondary rounded me-4 me-sm-0">
                                <img src="/static/assets/img/illustrations/job.svg">
                            </div>
                            <div class="d-sm-none">
                            </div>
                        </div>
                        <div class="col-12 col-xl-7 px-xl-0">
                            <div class="d-none d-sm-block">
                                <h2 class="h6 text-gray-400 mb-0">Active Jobs</h2>
                                <h3 class="fw-extrabold mb-2">{{job_count}}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-xl-4 mb-4">
            <div class="card border-0 shadow">
                <div class="card-body">
                    <div class="row d-block d-xl-flex align-items-center">
                        <div class="col-12 col-xl-5 text-xl-center mb-3 mb-xl-0 d-flex align-items-center justify-content-xl-center">
                            <div class="icon-shape icon-shape-secondary rounded me-4 me-sm-0">
                                <img src="/static/assets/img/illustrations/forms.svg">
                            </div>
                            <div class="d-sm-none">
                            </div>
                        </div>
                        <div class="col-12 col-xl-7 px-xl-0">
                            <div class="d-none d-sm-block">
                                <h2 class="h6 text-gray-400 mb-0">Unresolved Complaints</h2>
                                <h3 class="fw-extrabold mb-2">{{complaint_count}}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-12 col-xxl-6 mb-4">
            <div class="card border-0 shadow">
                <div class="card-header border-bottom d-flex align-items-center justify-content-between">
                    <h2 class="fs-5 fw-bold mb-0">Employees</h2>
                    <a href="{{url_for('manager_blueprint.manage_employees')}}" class="btn btn-sm btn-primary">See all</a>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush list my--3">
                        {% for employees in employee[0:5] %}
                        <li class="list-group-item px-0">
                            <div class="row align-items-center">
                                <div class="col-auto ms--2">
                                    <h4 class="h6 mb-0">
                                        <a href="#">{{employees.first_name}} {{employees.last_name}}</a>
                                    </h4>
                                    <div class="d-flex align-items-center">
                                        <small>{{employees.trn}}</small>
                                    </div>
                                </div>
                                <div class="col text-end">
                                    <a href="{{url_for('manager_blueprint.view_employee', trn=employees.trn)}}" class="btn btn-sm btn-secondary d-inline-flex align-items-center">
                                        <svg class="icon icon-xxs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z" clip-rule="evenodd"></path></svg>
                                        View
                                    </a>
                                </div>
                            </div>
                        </li>
                        {%endfor%}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-12 col-xxl-6 mb-4">
            <div class="card border-0 shadow">
                <div class="card-header border-bottom d-flex align-items-center justify-content-between">
                    <h2 class="fs-5 fw-bold mb-0">Active Jobs</h2>
                    <a href="{{url_for('manager_blueprint.manage_jobs')}}" class="btn btn-sm btn-primary">See all</a>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush list my--3">
                        {% for jobs in job[0:5] %}
                        <li class="list-group-item px-0">
                            <div class="row align-items-center">
                                <div class="col-auto ms--2">
                                    <h4 class="h6 mb-0">
                                        <a href="#">Job ID: {{jobs.ref_number}}</a>
                                    </h4>
                                    <div class="d-flex align-items-center">
                                        <medium>Description: {{jobs.description}}</medium>
                                    </div>
                                    <div class="d-flex align-items-center">
                                        <small>{{jobs.fk_supervisor}}</small>
                                    </div>
                                </div>
                                <div class="col text-end">
                                    <a href="{{url_for('manager_blueprint.view_jobs', id=jobs.ref_number)}}" class="btn btn-sm btn-secondary d-inline-flex align-items-center">
                                        <svg class="icon icon-xxs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z" clip-rule="evenodd"></path></svg>
                                        View
                                    </a>
                                </div>
                            </div>
                        </li>
                        {%endfor%}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-12 col-xxl-6 mb-4">
            <div class="card border-0 shadow">
                <div class="card-header border-bottom d-flex align-items-center justify-content-between">
                    <h2 class="fs-5 fw-bold mb-0">Complaints</h2>
                    <a href="{{url_for('manager_blueprint.manage_complaints')}}" class="btn btn-sm btn-primary">See all</a>
                </div>
                <div class="card-body">
                    <ul class="list-group list-group-flush list my--3">
                        {% for complaints in complaint[0:5] %}
                        <li class="list-group-item px-0">
                            <div class="row align-items-center">
                                <div class="col-auto ms--2">
                                    <h4 class="h6 mb-0">
                                        <a href="#">Job ID: {{complaints.fk_job}} </a>
                                    </h4>
                                    <div class="d-flex align-items-center">
                                        <medium>Date:{{complaints.date}}</medium>
                                    </div>
                                </div>
                                
                                <div class="col text-end">
                                    <a href="{{url_for('manager_blueprint.view_complaints', id=complaints.fk_job, resident=complaints.fk_resident, date=complaints.date)}}" class="btn btn-sm btn-secondary d-inline-flex align-items-center">
                                        <svg class="icon icon-xxs me-2" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 5v8a2 2 0 01-2 2h-5l-5 4v-4H4a2 2 0 01-2-2V5a2 2 0 012-2h12a2 2 0 012 2zM7 8H5v2h2V8zm2 0h2v2H9V8zm6 0h-2v2h2V8z" clip-rule="evenodd"></path></svg>
                                        View
                                    </a>
                                </div>
                            </div>
                        </li>
                        {%endfor%}
                    </ul>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %} 
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="/static/assets/js/datatables-simple-demo.js"></script>
{% endblock javascripts %}

app/templates/manager/manage-employees.html
{% extends "layouts/manager/base.html" %}

{% block title %} Tables {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="py-4">
      <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
          <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
              <li class="breadcrumb-item">
                  <a href="/manager/dashboard">
                      <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6"></path></svg>
                  </a>
              </li>
              <li class="breadcrumb-item active" aria-current="page">Employees</li>
          </ol>
      </nav>
      <div class="d-flex justify-content-between w-100 flex-wrap">
          <div class="mb-3 mb-lg-0">
              <h1 class="h4">Employees Table</h1>
              <p class="mb-0">Below are a list of all employees</p>
          </div>
      </div>
  </div>

  <div class="card border-0 shadow">
    <div class="card-header">
        <i class="fas fa-table me-1"></i>
        <a class="btn btn-primary" href="/manager/add-employees/regular" role="button">Add Regular Employee</a>
        <a class="btn btn-primary" href="/manager/add-employees/temporary" role="button">Add Temporary Employee</a>
    </div>
      <div class="card-body">
          <div class="table-responsive">
              <table id="datatablesSimple" class="table table-centered table-nowrap mb-0 rounded">
                  <thead class="thead-light">
                      <tr>
                          <th class="border-0 rounded-start">TRN</th>
                          <th class="border-0">First Name</th>
                          <th class="border-0">Last Name</th>
                          <th class="border-0">Street Num</th>
                          <th class="border-0">Street Name</th>
                          <th class="border-0">City</th>
                          <th class="border-0">Parish</th>
                          <th class="border-0">Auditor</th>
                          <th class="border-0 rounded-end">Options</th>
                      </tr>
                  </thead>
                  <tbody>
                      <!-- Item -->
                      {% for employee in all_employees %}
                      <tr>
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ employee.trn }}</span></div>
                            </a>
                        </td>
                          <td class="border-0">                                             
                              <a href="#" class="d-flex align-items-center">
                                  <div><span class="h6">{{ employee.first_name }}</span></div>
                              </a>
                          </td>
                          <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ employee.last_name }}</span></div>
                            </a>
                        </td>
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ employee.street_num}}</span></div>
                            </a>
                        </td>
                        
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ employee.street_name}}</span></div>
                            </a>
                        </td>
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ employee.city}}</span></div>
                            </a>
                        </td>
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ employee.parish}}</span></div>
                            </a>
                        </td>
                        <td class="border-0">                                             
                            <a href="#" class="d-flex align-items-center">
                                
                                <div><span class="h6">{{ employee.auditor}}</span></div>
                            </a>
                        </td>
                        <td>
                            <a class="btn btn-primary" href="{{url_for('manager_blueprint.view_employee', trn=employee.trn)}}" role="button">View</a>  
                            <a class="btn btn-primary" href="{{url_for('manager_blueprint.promote_employee', trn=employee.trn)}}" role="button">Promote Employee</a>
                            <a class="btn btn-primary" href="{{url_for('manager_blueprint.otp_verify_employee', trn=employee.trn)}}" role="button">Remove</a>   
                          </td>
                      </tr>
                      <!-- End of Item -->
                      {% endfor %}
                  </tbody>
              </table>
          </div>
      </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}

<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="/static/assets/js/datatables-simple-demo.js"></script>

{% endblock javascripts %}

app/templates/manager/promote-temporary.html
{% extends 'layouts/manager/base.html' %} {% block title %} Profile {% endblock
    title %} {% block content %}
    <!-- Page content -->
    <br>
    <div class="container-fluid mt--6">
      <div class="row">
        <div class="col-xl-8 order-xl-1">
          <div class="card">
            <div class="card-header">
              <div class="row align-items-center">
                <div class="col-8">
                  <h3 class="mb-0">Promote Temporary Employee</h3>
                </div>
              </div>
            </div>
            
            <div class="card-body">
              <form role="form" method="post" action="">
                {{ form.csrf_token }}
    
                <div class="col-md-4 position-relative">
                  <label for="validationTooltip02" class="form-label"
                    >New Wage</label
                  >
                  {{ form.hr_wage(type="number", class="form-control" ) }}
                </div>
                <div class="col-md-4 position-relative">
                  <label for="validationTooltip02" class="form-label"
                    >Update contract</label
                  >
                  {{ form.contract(type="Text", class="form-control" ) }}
                </div>
                <br />
                <div class="col-12">
                  <button class="btn btn-primary" name="add" type="submit">
                    Submit form
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    {% endblock content %}
    
    <!-- Specific JS goes HERE -->
    {% block javascripts %}{% endblock javascripts %}
    